numero=float(input('Digite um número: '))
dobro=(numero*2)
triplo=(numero*3)
raiz=(numero*numero)
print('Estes são o dobro, triplo e a raiz quadrada do número escolhido: ', dobro,',', triplo,'e', raiz)
